theme: minima
# ๐ข GREEN SNAKE

<p align="center">
  <img src="https://upload.wikimedia.org/wikipedia/commons/6/64/Green_Snake_Vector.svg" width="200">
</p>

ุฃุจุณุท ูุนุจุฉ ุฏูุฏุฉ ููุงุณูููุฉ ุจููู ุฃุฎุถุฑ ูุงุจุถ ุจุงูุญูุงุฉ!

---

## โก ุงูุชุดุบูู ุงูุณุฑูุน

```bash
git clone https://github.com/username/green-snake.git
cd green-snake
python game.py
```

---

## ๐น๏ธ ุงูุชุญูู
- **ุฃุณูู ุงูููุจูุฑุฏ**: โ โ โ โ  
- **ุงููุณุงูุฉ**: ุฅููุงู/ุงุณุชุฆูุงู  
- **Esc**: ุฎุฑูุฌ

---

```python
# ุฑูุฒ ุจุณูุท ูู ุงููุนุจุฉ
class Snake:
    def __init__(self):
        self.body = [(100, 100)]
        self.direction = (1, 0)
```

---

๐ **ุงูุชุฑุฎูุต**: [MIT](LICENSE)
